### ISSUE TITLE
Add feature to mockgen to support picking an interface from a source file

### ISSUE THREAD

**Issue by DanMass** [nmiodice/terraform-azure-devops-hack#22]
In https://github.com/golang/mock/blob/master/mockgen/mockgen.go add a flag for "interface"  to allow the user to pick a single interface from the source file from which to generate a mock file.

**Comment by nmiodice** [comment]
Closing in favor of backlog in new project repository: https://github.com/microsoft/terraform-provider-azuredevops/issues
