### ISSUE TITLE
Refactor project packaging for proper Go namespacing

### ISSUE THREAD

**Issue by TechnicallyWilliams** [nmiodice/terraform-azure-devops-hack#29]
Current unit tests are living within the main package/namespace but should be in their own package/namespace. This invites us to rethink the overall project packaging structure and may require a project packaging structure that more directly conforms to go conventions. 

For example, GoMock framework auto generates files when executing commands to mock interfaces and the framework assumes users will specify their project's custom testing package/namespace as an argument for the auto generate files to live in.

**Comment by nmiodice** [comment]
Closing in favor of backlog in new project repository: https://github.com/microsoft/terraform-provider-azuredevops/issues
