### ISSUE TITLE
Script a text parser that will transform client api plain text into an interface

### ISSUE THREAD

**Issue by TechnicallyWilliams** [nmiodice/terraform-azure-devops-hack#30]
Client apis where we desire an interface come with a lengthy list of operations coupled with their implementation details. (https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/core/client.go)

Scripting a text parser that will transform clipboard pasted api definitions into a simple interface by ignoring implementation details could pay dividends for current and potentially new clients. A script that auto stubs interface methods  for a client will likely use some combination of "grep" and "awk" commands

**Comment by nmiodice** [comment]
Closing in favor of backlog in new project repository: https://github.com/microsoft/terraform-provider-azuredevops/issues
