### ISSUE TITLE
Implement unit tests for provider and resources

### ISSUE THREAD

**Issue by awkwardindustries** [nmiodice/terraform-azure-devops-hack#38]
Although we have several foundational implementations for our resources, we do not have unit tests created for all of our resources yet at this time.

Minimally require coverage of:
- [ ] Project creation
- [ ] Project read
- [ ] ~~Project update~~ *Not yet implemented*
- [ ] ~~Project delete~~ *Not yet implemented*
- [ ] Pipeline creation
- [ ] Pipeline read
- [ ] Pipeline update
- [ ] Pipeline delete
- [ ] Service connection creation
- [ ] ~~Service connection read~~ *Not yet implemented*
- [ ] ~~Service connection update~~ *Not yet implemented*
- [ ] ~~Service connection delete~~ *Not yet implemented*

Additionally, we should:
- [ ] Add documentation covering how to update the `azdo_config.go` and generate the `mock_azdo_client.go`
- [ ] Add more useful tests to `provider_test.go`

**Comment by nmiodice** [comment]
Closing in favor of backlog in new project repository: https://github.com/microsoft/terraform-provider-azuredevops/issues
