### ISSUE TITLE
Implement more broad / general service connection resource

### ISSUE THREAD

**Issue by awkwardindustries** [nmiodice/terraform-azure-devops-hack#40]
Currently the only supported service connection is a GitHub service connection. This resource should be extended to support all possible service connections. This will also require refactoring to support optional parameters per type of service connection (e.g., `github_service_endpoint_pat`).

**Comment by nmiodice** [comment]
Closing in favor of backlog in new project repository: https://github.com/microsoft/terraform-provider-azuredevops/issues
